# Generated by Django 5.2.7 on 2025-10-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
